DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id INT AUTO_INCREMENT NOT NULL,
  email VARCHAR(128) NOT NULL,
  username VARCHAR(64) NOT NULL,
  password_hash BINARY(64) NOT NULL,
  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS tokens;
CREATE TABLE tokens (
  id INT NOT NULL,
  token_hash BINARY(64) NOT NULL,
  time_created DATETIME NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (id) REFERENCES users(id)
);
